### ISSUE TITLE
No login authentication 

### ISSUE THREAD

**Issue by sarvesh-sharma-yral** [yral-dapp/yral-mobile#1]
Setup no login auth wrt the following context:
<img width="636" alt="Screenshot 2024-11-06 at 8 00 15 PM" src="https://github.com/user-attachments/assets/ce52482e-ef68-40f5-bc4b-527f24218547">

- [x] #2
- [x] #6
- [x] #7
- [x] #12
- [x] #13
- [x] #8
- [x] #9

**Comment by harshita-srivastava-yral** [comment]
- Penned down the flows and documented them
- 3rd Party library has been identified
- JWK http cookie we are that script
- By tomorrow we can get this closed

**Comment by harshita-srivastava-yral** [comment]
- We are targeting today to close the sub issues in the task

**Comment by harshita-srivastava-yral** [comment]
- All the subissues in this tasks is expected to be closed today

**Comment by harshita-srivastava-yral** [comment]
-> Authentication is done
-> Few functions are remaining 
-> working with Rupansh to have a better version of it
