### ISSUE TITLE
Add ffi binding using swift-bridge for the remaining did files

### ISSUE THREAD

**Issue by sarvesh-sharma-yral** [yral-dapp/yral-mobile#15]
Just like the ffi bindings have been added for individual_user_template.did, add the ffi binding using swift-bridge for the remaining did files from https://github.com/yral-dapp/yral-common/tree/master/canisters-client/did
- [x] #16
- [x] #17
- [x] #18

**Comment by harshita-srivastava-yral** [comment]
- This should be done by tomorrow first half
- @komal-sai-yral to review the PRs (Anyone who has bandwidth)
